<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>
<script src="/js/jquery.js"></script>
<style>
.content img 
{
border: none!important;

}

</style>
<script>
	var HOST = 'http://xxxxxx.xx';
	var CURURL = '';
	var CURWIKIURL  = '';
	var TOKEN;
	var map;
	var locenableHighAccuracy = true;
        var loctimeout = 10000;
        var locmaximumAge = 120000;
        var markers = [];
	function makeviewindex()
	{
	  $('#content').height($(window).height()-($('#header').height() + $('#footer').height() + (parseInt($('#content').css('padding'))  * 2) + 4));
	}
	function maker(Latlng)
	{
	 var image = {
          url: '/i/point_32_1_green.png',
          // This marker is 20 pixels wide by 32 pixels tall.
          size: new google.maps.Size(32, 32),
          // The origin for this image is 0,0.
          origin: new google.maps.Point(0,0),
          // The anchor for this image is the base of the flagpole at 0,32.
          anchor: new google.maps.Point(16, 16)
        };
	  var marker = new google.maps.Marker({
            position: Latlng,
            title: '',
            icon: image
	  });
	  return marker;
        
	}
	function clearMap()
	{
	  $.each(markers, function(key, val) {
	    val.setMap(null);
	  });
	  markers = [];
	}
	
	function getLocations()
	{
	  $.ajax({
	  url: "/gts/listlocations/?callback=?",
	  cache: false,
	  dataType:'jsonp'
	  }).done(function( data ) {
	    console.log(data);
	    clearMap();
	    $.each(data.data, function(key, val) {
		var myLatlng = new google.maps.LatLng(val.lat,val.lng);
		 console.log(val.lat);
		 console.log(val.lng);
		 console.log('----');
		var m = maker(myLatlng);
		markers.push(m);
		m.setMap(map);
	    });
	  });

	}

	$(document).ready(function(){
		var mapOptions = {
				zoom: 10,
				mapTypeId: google.maps.MapTypeId.SATELLITE
				  };
		map = new google.maps.Map(document.getElementById('map'), mapOptions);
		var pos = new google.maps.LatLng(56,60);
		map.setCenter(pos);
	});
	google.maps.event.addDomListener(window, 'load', getLocations);
	</script>
<div class="map" id="map" style="height:500px; width:100%"></div>
	