<h2>Смена пароля</h2>
<form action="/auth/change-password" method="post">
<div id="login_form">
<div id="login_result">
<?
if (!$this->isPost) {
if (!$this->ok) {?>
<? print $this->error;  ?>
<? } else {?>
Пароль сменен
<? }
}?>
</div>
Старый пароль:<br /><input  type="password"  id="oldPassword" name="oldPassword"><br /><br />
Новый пароль:<br /><input type="password" id="password1"  name="password1" size="10"> ещё раз:
<input type="password" id="password2"  name="password2"  size="10"><br /><br />
<input type="submit"  value="Сменить"/>
</div>
</form>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<br />
