<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no">
	<title><? echo $this->t; ?></title>
	<link rel="stylesheet"  href="/subs_images/css/metro.css" />
	<link rel="stylesheet"  href="/subs_images/css/style.css" />
	<script src="js/jquery.js"></script>
</head>
<body>
<div data-role="page" data-there="a" class="mainpage">
<div data-role="header" id="header" class="header">
<? echo $this->t; ?>
</div> 
<div class="content" id="content">
<? echo $this->cnt; ?>
</div>
</body>
</html>
