Большие файлы могут не отображаться - проблемы у гугла.
<form action="" method="post"  enctype="multipart/form-data">
<input type="text" name="name" size="50"><br />
<input type="file" name="file"><br />
<input type="submit" value="Upload"><br /><br />
</form>
<script>
var test_url = '47t5435346357dfsjf.kml';
var store_path = "<? print $this->store_path;?>";
var host_url =  window.location.protocol+'//'+window.location.hostname+'/';
function file_load(event,file)
{
  event = event || window.event;
  var filename = host_url+store_path+'/'+file;
 // alert(filename);
  window.parent.load_kml(filename);
  alert('OK');        
  event.stopPropagation ? event.stopPropagation() : (event.cancelBubble=true)
  event.preventDefault ? event.preventDefault() : (event.returnValue=false)
}
function download(event,file)
{
  event = event || window.event;
  var filename = host_url+store_path+'/'+file;
  document.getElementById('download').src = filename;
  alert('OK');
  event.stopPropagation ? event.stopPropagation() : (event.cancelBubble=true)
  event.preventDefault ? event.preventDefault() : (event.returnValue=false)
}
</script>
<iframe id="download" src="about:blank" width="0" height="0"></iframe>
<br /><br /><br /><br />
<!-- nput type="button" onclick="test_load(test_url)" value="test_load" -->
<ul>
<?php foreach($this->kml_list as $item) { ?>
<li><a href="#" onclick="file_load(event,'<? print $item['filename']; ?>')"><? print $item['name']; ?></a>
<small><a href="#" onclick="download(event,'<? print $item['filename']; ?>')">dnld</a></small></li>
<?php } ?>
</ul>
