<div class="content">
<h2>Контакты</h2>
По всем вопросом вы можете связать с нами по
Email: <a href="mailto:info@twmap.ru">info@twmap.ru</a><br />
Так же вы можете узнавать о новостях и обновления в твиттере
<a href="http://twitter.com/twi_map" target="_blank"><img src="http://twitter-badges.s3.amazonaws.com/t_mini-a.png" alt="Twi_map" border="0" /> Twi_map</a> <br />
Записи о нашем проекте вы можете найти по
 хэш-тегу: <a href="http://search.twitter.com/search?q=%23twimap" target="_blank">#twimap</a><br />
 <br /> <br />
 <ul>
 <li><a href="http://www.google.com/intl/ru-RU_US/help/terms_maps.html" target="_blank">Google Maps/Earth Terms of Service</a></li>
 <li><a href="http://wiki.openstreetmap.org/wiki/Tile_usage_policy">OpenStreetMap Tile usage policy</a></li>
 </ul>
</div>