<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>Impact of UFOs and anthropogenic factors</title>
<link rel="stylesheet" type="text/css" href="css/styles.css" media="screen" />
<script type="text/javascript" src="/js/mootools-core-1.3-full-compat-yc.js"></script>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <script type="text/javascript" src="js/map/MapTypesControl.js"></script>
        <script type="text/javascript" src="js/map/ZoomControl.js"></script>
      
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <script type="text/javascript" src="js/window/h.js"></script>
        <script type="text/javascript" src="js/window/w.js"></script>

<script type="text/javascript">
  var loged = <?=$this->loged;?>;
  var login = "<?=$this->login;?>";
  var view_name = "<?=$this->view_name;?>";
</script>
<script type="text/javascript" src="js/main.js"></script>
</head>
<body>
<div id="map"></div>
<div id="opdiv" class="control opacity30"> </div>
<div id="controls" class="control">
<div id="buttons" class=""></div><div id="maptypes" class="opacity100"></div>
</div>
<div id="zoom">
</div>
</body>
</html>
