<?=$this->doctype(XHTML1_TRANSITIONAL)?>
<html>
 <head>
  <? $page_title = $this->page_title ? $this->page_title : '';?>
  <?=$this->headTitle($page_title)?>
  <?=$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')?>
  <!-- script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools.js"></script -->
  <script type="text/javascript" src="/js/mootools-1.2.4-core.js"></script>
  <link href="/css/styles.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
<?=$this->layout()->content?>

<script src="http://mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounterXXXXXXX = new Ya.Metrika(XXXXX); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="http://mc.yandex.ru/watch/XXXXXXX" alt="" /></div></noscript>

</body>
</html>