<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://gmpg.org/xfn/11">
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="imagetoolbar" content="no" />
        <link rel="stylesheet" href="/css/cssf-base.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/css/wiki.css" type="text/css" media="screen" />
        <!--[if lte IE 6]><link rel="stylesheet" href="css/cssf-ie6.css" type="text/css" media="screen" /><![endif]-->
        <!--[if IE 7]><link rel="stylesheet" href="css/cssf-ie7.css" type="text/css" media="screen" /><![endif]-->
        <script type="text/javascript" src="/js/common.js"></script>
        <script type="text/javascript" src="/js/iepngfix_tilebg.js"></script>
        <!--[if IE]><script type="text/javascript" src="js/excanvas.js"></script><![endif]-->
</head>
<body>
<div id="page">
<div class="page-layout">
<div class="container"><div class="layout-box lb-1 corners corners-10 style="background: #ccc;"">
</div></div>
</div>
                <div class="container">
                        <div class="layout-box lb-1">
                                <div class="box content">
                                   <?=$this->layout()->content?>
                                </div>
                        </div><!-- layout-box -->
                </div><!-- container -->

                <div class="container">
                        <div class="layout-box lb-1">

                        </div><!-- layout-box -->
                </div><!-- container -->

        </div><!-- page-layout -->

</div><!-- #page -->

<script type="text/javascript">
        CornersInit();
</script>
</body>
</html>
