<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "wiki",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,
        content_css : "css/example.css",
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        },
        autosave_ask_before_unload : false // Disable for example purposes
});

</script>
<!-- --->
<ul class="wikipath">
<?php
//print '<pre>'; print_r($this->pathItemsData); print '</pre>';
$pathItemsDataCount = count($this->pathItemsData);
$pathItemsDataCount_min_one = $pathItemsDataCount-1;
for($i=0;$i<$pathItemsDataCount;$i++ ) {
        $item1 = $this->pathItemsData[$i];
        if($i != $pathItemsDataCount_min_one) {
 ?>
<li><a href="/wiki<?php print $item1['path']; ?>"><?php print $item1['title']; ?></a></li>
<?php } else { ?>
<li><?php print $item1['title']; ?></li>
<?php }  ?>
<?php } ?>
</ul>
<!-- --->
<?php if(!empty($this->error)) { ?>
<div style="border: border: 1px solid black; padding: 5px; margin: 7px; width: 100%; background-color: #cacaca">
<?php print $this->error; ?>
</div>
<?php } ?>
<form action="" method="post" class="wikiform">
<div id="titlediv">
Заголовок: <input type="text" name="title" id="title" value="<? print htmlspecialchars($this->wikiData->title);?>">
</div>

<textarea name="text" rows="10" cols="25" style="width:100%; height: 300px"><? print $this->wikiData->text; ?></textarea><br /><br />
<input type="submit" name="Save">
</form>
